# PRIMITIVE 

# int = 24 67 54 87 95 23 65 12 99 26

# float = 9.7 3.4 5.1 3.9 4.6 7.2 3.5 6.8 1.4 9.2

# alpha = Michael Jackson Daddy Mummy Devnaija 

# alphanumeric =  Michael34 Jackson50 Daddy13 Mummy27 Devnaija45

# myname = "Emmanuel"
# myname = "Matthew"
# myage = 10
# myage = 7
# print(myname)

# myname = "emma"
# myage = 10
# myclass = 6

# print(f"my name is {myname} i am {myage} years old, and i am in class {myclass}.")
# myname = "Matthew"
# print(len(myname))
# myname = "Emmanuel"
# print(myname.upper())
# name = "matthew"

# print(name.replace("matthew" ,"matt"))

# myname = "Jireh"
# print(myname.replace("Jireh", "Zion"))

# assignments:
# create a variable mycountry = America (replace with Australia)

# create a variable mybestfriend = jojo (make jojo to uppercase)

# mycountry = "Nigeria"
# print(mycountry.replace("Nigeria", "New Zeland"))

# mybestfriend = "Zac"
# print(mybestfriend.upper())

# food = ["KFC","Rice","Pinapple","Grapes"]
# print(food) 

# number = [7,10,36,40,67,98,123]
# print(number)
# print(food[3])
# print(number[3])
# print(food[0])
# print(food[1])
# print(food[2])

# fruits = ['Banana', 'Mango']
# print(fruits)
# fruits.append('stawberry')
# print(fruits)
# fruits.append("apple")
# print(fruits)

# food = ['Sandwich','Chips','Noodles','Apple Juice']
# print(food)
# food.remove('Sandwich')
# print(food)
# food.remove("Chips")
# print(food)
# food.remove("Apple Juice")
# print(food)
# food.remove("Noodles")
# print(food)
# food = ['Sandwich','Chips','Noodles','Apple Juice']
# print(food)
# food.clear()
# print(food)
# create a list of an item with just one item.
# use append to add more items up to 5



# Pastors = ('Jerry Eze','Joshua Selman','Emmanuel Iren','Femi Lazarus')
# print(len(Pastors))
# del Pastors
# print(Pastors)

# drinks = {'Water','Fanta','Coke'}
# print(drinks)
 
# #  assignment 
# # add three more drinks to the set.

# drinks.add("Sprite")
# drinks.add("L&P")
# drinks.add("applejuice")
# print(drinks)
# drinks.remove("Coke")
# drinks.remove("L&P")
# drinks.remove("applejuice")
# print(drinks)
# drinks.clear()
# print(drinks)

# Tigers = {'Begal','Siberian'}
# Tigers.add("Sumatran")
# Tigers.add("Malayan")
# Tigers.add("Indochines")
# Tigers.add("South China")
# Tigers.add("Javin")
# Tigers.add("Bail")
# Tigers.add("Caspian")
# print(Tigers)
# Tigers.remove("Javin")
# Tigers.remove("South China")
# print(Tigers)
# create a set of 2 football players
# then use add to add 5 more football
# players.

# Football = {'Messi','Ronaldo'}
# Football.add("Zlatan")
# Football.add("Neymar Jr")
# Football.add("Mbappe")
# Football.add("Salah")
# Football.add("Saka")
# Football.remove('Zlatan')
# print(Football)

# Friend = {"name":'Zac',"lastname":"McNicholas","age":7}
# print(Friend)

# Friend = {"name":'Zachary',"lastname":"Lister","Age":10}
# # print(Friend)

# print(Friend.get('lastname'))
# print(Friend.get('name'))
# print(Friend.get('Age'))

# print(Friend.get('name'))
# print(Friend.get('lastname'))
# print(Friend.get('age'))

# Add your favourite game in Roblox 
# and favourite movie using update

# Friend.update({"favourite game":"Piggy","favourite movie":"Ninjago"})
# print(Friend)
# Friend.pop("name")
# print(Friend)

# Friend.pop("favourite movie")
# print(Friend)
# Friend.clear()
# print(Friend)
# def lol():
#     print("vanilla&chocolate")
# lol()
# lol()
# lol()
# lol()
# lol()
    
# def bird():
#     print("sea animals")
# bird()    
# bird()    
# bird()    
# bird()    
# bird()    
# bird()    
# bird()    
# bird()    

# def jump():
#     print("grass")

# jump()
# jump()  
# jump()  
# jump()  


# def Burning():
#     print("Sun")
# Burning()    
# Burning()    
# Burning()    
# Burning()    

# def cash():
#     print("games")
# cash()
# cash()
# cash()
# cash()

# def favfood(food):
#    print(f"my favourite food is {food}.")
# favfood("Sausage rolls")


# def favgame(game):
#    print(f"my favourite game is {game}")
# favgame("bloxfruits.")
# favgame("fortline.")
# favgame("rivals.")
# favgame("brookhaven.")

# def fav(drink,snacks):
#     print(f"my favourite {drink} and {snacks}") 
# fav('coke','pizza')

# def fav(drink,snacks):
#     print(f"my favourite {drink} and {snacks}")
# fav('water','pizza')    

# def fav(instrument):
#     print(f"my favourite {instrument}")
# fav('piano')

# def fav(instrument):
#     print(f"my favourite {instrument}")
# fav('piano')

# def fav(sport):
#     print(f"my favourite {sport}")
# fav('Danish')   

# def fav(sport):
#     print(f"my favourite {sport}")
# fav('Football')  

# def fav(song):
#     print(f"my favourite song {song}")
# fav('you too dey bless me')    

 
# def fav(song):
#     print(f"my favourite song {song}")
# fav('Lion of Judah') 

# def fav(season,shop,singer):
#     print(f"my favourite season is {season},my favourite shop is {shop},my favourite singer is {singer}")
# fav('summer','thewarehouse','Michael Jackson')

# def fav(sport,country,planet):
#    print(f"my favourite sport is {sport},my favourite country is {country},my favuorite planet is {planet}")
# fav("football","china","jupiter")   
# def fav(youtuber,dance,animal,color):
#     print(f"my favourite youtuber is {youtuber},my favourite dance is {dance},my favourite animal is {animal},my favourite color is {color}")
# fav("tappy","circle glide","tiger","orange")

# def fav(youtuber,dance,animal,color):
#     print(f"my favourite youtuber is {youtuber},my favourite dance is {dance},my favourite animal is {animal},my favourite color is {color}")
# fav("tappy","moonwalk","lion","Blue")

# d = 1000
# i = 1600

# if(i > d):
#     print("i is greater than d")
# else:
#     print("i is less than d")
#  A = 9

# if(E > A):
#     print("E is greater than A")
# else:
#     print("E is less than A")   
# E = 10

# S = 8
# F = 5

# if(S == F):
#     print("True")
# else:
#     print("False")  

# g = 7
# j = 7

# if(g == j):
#     print("true")
# else:
#     print("false")

# def add(k,j): 
#    print(k/j)
# add(132,11)   
 

# def add(w,r):
#    print(w*r)
# add(8,7)     

# def add(T,X):
#    print(T-X)
# add(74,39)   

# people = ['Alcryse','Emmanuel','Semilore','Zachary']

# for x in people:
#     print(f"My name is " + x)

# people = ['Zac','Matthew','Blake','Awanui']

# for x in people:
#     print(f"my name is " + x )

# print(f"What is the name of your teacher")

# one = 'Mrs Clark'
# two = 'Mr Riley'
# three = "Miss B-E"
 
# answer = input() 

# if answer == 'one':
#     print('wrong answer')
# elif answer == 'two':
#     print('wrong answer') 
# else:
#     print('correct answer')    

# print(f"What is the name of my favourite car")      
# one = 'Porsche' 
# two = 'Mercedes Benz'
# three = 'Audi'

# answer = input()

# if answer == 'one':
#     print('correct answer')
# elif answer == 'two':
#     print('wrong answer')    
# else:
#     print('wrong answer')

# print(f"What is the name of my favourite car")      
# one = 'Pagani' 
# two = 'Bugatti'
# three = 'Lamborghini'

# answer = input()

# if answer == 'one':
#     print('wrong answer')
# elif answer == 'two':
#     print('correct answer')    
# else:
#     print('wrong answer')

# import random

# def number_guessing_game():
#     name = input("hello what is your name? ")
#     print(f"Welcome {name} to the Number Guessing game")
#     secret_number = random.randint(1,20)
#     attempts = 0

#     while True:
#         guess = int(input("guess a number beetween 1 and 20 ="))
#         attempts += 1

#         if guess < secret_number:
#             print("Too low")
#         elif  guess > secret_number:
#             print("Too high")
#         else:
#             print(f"Congatulations! you guessed the number in {attempts} attempts.")
#             break
# number_guessing_game()      


# import random

# def number_guessing_game():
#     name = input("hello what is your name? ")
#     print(f"Welcome {name} to the Number Guessing game")
#     secret_number = random.randint(1,10)
#     attempts = 0

#     while True:
#         guess = int(input("guess a number beetween 1 and 10 ="))
#         attempts += 1

#         if guess < secret_number:
#             print("Too low")
#         elif  guess > secret_number:
#             print("Too high")
#         else:
#             print(f"Congatulations! you guessed the number in {attempts} attempts.")
#             break
# number_guessing_game()      


import random

def rock_paper_scissors():
    choices = ['rock', 'paper', 'scissors']
    computer_choice = random.choice(choices)

    player_choice = input("choose rock, paper, scissors: ").lower()

    if player_choice not in choices:
        print("invalid choice, please choose again")
    else:
        print(f"Computer chose {computer_choice}.")
        if player_choice == computer_choice:
            print("It's a tie ")
        elif (player_choice == 'rock' and computer_choice == 'scissors')  or \
            (player_choice == 'scissors' and computer_choice == 'paper') or \
            (player_choice == 'paper' and computer_choice == 'rock'):
            print("You win!:)") 
        else:
            print("You lose!:(")    

rock_paper_scissors()            